"""Pydantic schemas and data models for Listening Service."""

from typing import List, Optional
from pydantic import BaseModel, Field


class ExtractTranscriptRequest(BaseModel):
    """Payload for extracting YouTube transcript."""

    youtube_url: str = Field(..., description="YouTube video URL or Video ID")
    language: Optional[str] = Field(
        default="en", description="Preferred transcript language code"
    )


class BlankItem(BaseModel):
    """Represents a masked word in a fill-in-the-blank exercise."""

    index: int = Field(..., description="Position index of the blank in segment")
    original_word: str = Field(
        ..., description="The correct target word to be typed"
    )
    hint: str = Field(
        ..., description="Visual hint showing first letter and letter count"
    )


class Segment(BaseModel):
    """Represents a timestamped transcript segment."""

    id: int = Field(..., description="1-indexed segment identifier")
    start: float = Field(..., description="Start time in seconds")
    end: float = Field(..., description="End time in seconds")
    duration: float = Field(..., description="Segment duration in seconds")
    text: str = Field(..., description="Original segment subtitle text")
    masked_text: Optional[str] = Field(
        default=None, description="Text with blanks (e.g., 'Hello _____')"
    )
    blanks: Optional[List[BlankItem]] = Field(
        default=[], description="List of masked blank items"
    )


class ExtractTranscriptResponse(BaseModel):
    """Response payload containing video information and transcript segments."""

    video_id: str = Field(..., description="Extracted YouTube Video ID")
    language: str = Field(..., description="Language code of extracted transcript")
    is_generated: bool = Field(
        ..., description="True if captions were auto-generated by YouTube"
    )
    total_segments: int = Field(
        ..., description="Total count of transcript segments"
    )
    segments: List[Segment] = Field(
        ..., description="List of timestamped transcript segments"
    )


class ProcessVideoRequest(BaseModel):
    """Payload for processing YouTube video into a ready-to-use lesson."""

    youtube_url: str = Field(..., description="YouTube video URL or Video ID")
    title: Optional[str] = Field(
        default=None, description="Optional custom title for the lesson"
    )
    difficulty: Optional[str] = Field(
        default="medium",
        description="Exercise difficulty level: 'easy', 'medium', 'hard'",
    )
    is_published: Optional[bool] = Field(
        default=True,
        description="Admin visibility flag (True = public, False = admin only)",
    )


class ProcessVideoResponse(BaseModel):
    """Complete processed lesson payload for frontend practice."""

    video_id: str = Field(..., description="YouTube Video ID")
    title: str = Field(..., description="Lesson title")
    language: str = Field(..., description="Language code")
    is_published: bool = Field(..., description="Visibility status")
    total_segments: int = Field(..., description="Number of segments")
    segments: List[Segment] = Field(..., description="Interactive segments with blanks")
